version: '3.8'
services:
  backend:
    build: ./cloudapp/cloudapp
    container_name: cloudapp-backend
    ports:
      - "8080:8080"
    
  frontend:
    build: ./UI/cloudapp
    container_name: cloudapp-frontend
    ports:
      - "4200:80"
