spring:
    docker:
        compose:
            enabled: true

    datasource:
        url: jdbc:postgresql://localhost:5432/cloudapp
        username: ""
        password: ""
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ""
                        client-secret: ""
                        scope: profile, email
                        redirect-uri: "http://localhost:8080/login/oauth2/code/google"
                provider:
                    google:
                        user-name-attribute: sub

    frontend:
        redirectUrl: http://localhost:4200/oauth2/redirect

aws:
    region: eu-north-1
    s3:
        bucket-name: ""
    access-key: ""
    secret-key: ""
